export const PLOT_DATA_TYPES = {
  PLOT_DATA_FETCHING: "PLOT_DATA_FETCHING.PLOT_DATA_FETCHING",
  PLOT_DATA_FETCHED: "PLOT_DATA_FETCHED.PLOT_DATA_FETCHED",
  PLOT_DATA_FAILED: "PLOT_DATA_FAILED.PLOT_DATA_FAILED",

  PLOT_DATA_CHANGE_FETCHING:
    "PLOT_DATA_CHANGE_FETCHING.PLOT_DATA_CHANGE_FETCHING",
  PLOT_DATA_CHANGE_FETCHED: "PLOT_DATA_CHANGE_FETCHED.PLOT_DATA_CHANGE_FETCHED",
  PLOT_DATA_CHANGE_FAILED: "PLOT_DATA_CHANGE_FAILED.PLOT_DATA_CHANGE_FAILED",

  PLOT_DATA_UPDATE: "PLOT_DATA_TYPES.PLOT_DATA_UPDATE",
  PLOT_DATA_SDF_FORECAST_CHANGED:
    "PLOT_DATA_TYPES.PLOT_DATA_SDF_FORECAST_CHANGED",
};
