export const QUICK_FILTER_DATA_TYPES = {
  FILTER_DATA_FETCHING: "FILTER_DATA_FETCHING.FILTER_DATA_FETCHING",
  FILTER_DATA_FETCHED: "FILTER_DATA_FETCHED.FILTER_DATA_FETCHED",
  FILTER_DATA_FAILED: "FILTER_DATA_FAILED.FILTER_DATA_FAILED",

  QUICK_FILTER_DATA_FETCHING:
    "QUICK_FILTER_DATA_FETCHING.QUICK_FILTER_DATA_FETCHING",
  QUICK_FILTER_DATA_FETCHED:
    "QUICK_FILTER_DATA_FETCHED.QUICK_FILTER_DATA_FETCHED",
  QUICK_FILTER_DATA_FAILED: "QUICK_FILTER_DATA_FAILED.QUICK_FILTER_DATA_FAILED",

  TABLE_DATA_FETCHING: "TABLE_DATA_FETCHING.TABLE_DATA_FETCHING",
  TABLE_DATA_FETCHED: "TABLE_DATA_FETCHED.TABLE_DATA_FETCHED",
  TABLE_DATA_FAILED: "TABLE_DATA_FAILED.TABLE_DATA_FAILED",

  APPEND_TABLE_DATA_FETCHING:
    "QUICK_FILTER_DATA_TYPES.APPEND_TABLE_DATA_FETCHING",
  APPEND_TABLE_DATA_FETCHED:
    "QUICK_FILTER_DATA_TYPES.APPEND_TABLE_DATA_FETCHED",
  APPEND_TABLE_DATA_FAILED: "QUICK_FILTER_DATA_TYPES.APPEND_TABLE_DATA_FAILED",

  TIME_FILTER_DATA_FETCHING:
    "TIME_FILTER_DATA_FETCHING.TIME_FILTER_DATA_FETCHING",
  TIME_FILTER_DATA_FETCHED: "TIME_FILTER_DATA_FETCHED.TIME_FILTER_DATA_FETCHED",
  TIME_FILTER_DATA_FAILED: "TIME_FILTER_DATA_FAILED.TIME_FILTER_DATA_FAILED",
  DEFAULT_VALUE_CHANGED: "TIME_FILTER_DATA_FAILED.DEFAULT_VALUE_CHANGED",

  ADD_DFU_ROW_FETCHING: "QUICK_FILTER_DATA_TYPES.ADD_DFU_ROW_FETCHING",
  ADD_DFU_ROW_FETCHED: "QUICK_FILTER_DATA_TYPES.ADD_DFU_ROW_FETCHED",
  ADD_DFU_ROW_FAILED: "QUICK_FILTER_DATA_TYPES.ADD_DFU_ROW_FAILED",

  ADD_DFU_ROW_CHANGED: "QUICK_FILTER_DATA_TYPES.ADD_DFU_ROW_CHANGED",
  TIME_FILTER_TYPE_CHANGED: "QUICK_FILTER_DATA_TYPES.TIME_FILTER_TYPE_CHANGED",
  QUICK_FILTER_CHANGE: "QUICK_FILTER_DATA_TYPES.QUICK_FILTER_CHANGE",
  RESET_ADD_DFU_TABLE: "QUICK_FILTER_DATA_TYPES.RESET_ADD_DFU_TABLE",
  UPDATE_TABLE_DATA: "QUICK_FILTER_DATA_TYPES.UPDATE_TABLE_DATA",
  GET_TABLE_CELL: "QUICK_FILTER_DATA_TYPES.GET_TABLE_CELL",
  TIME_FILTER_DATE_CHANGE: "QUICK_FILTER_DATA_TYPES.TIME_FILTER_DATE_CHANGE",
};
