export const FINAL_SUBMISSION_TYPES = {
  SAVE_DFU_TABLE_FETCHING: "FINAL_SUBMISSION_TYPES.SAVE_DFU_TABLE_FETCHING",
  SAVE_DFU_TABLE_FETCHED: "FINAL_SUBMISSION_TYPES.SAVE_DFU_TABLE_FETCHED",
  SAVE_DFU_TABLE_FAILED: "FINAL_SUBMISSION_TYPES.SAVE_DFU_TABLE_FAILED",

  DFU_TABLE_EXPORT_FETCHING: "FINAL_SUBMISSION_TYPES.DFU_TABLE_EXPORT_FETCHING",
  DFU_TABLE_EXPORT_FETCHED: "FINAL_SUBMISSION_TYPES.DFU_TABLE_EXPORT_FETCHED",
  DFU_TABLE_EXPORT_FAILED: "FINAL_SUBMISSION_TYPES.DFU_TABLE_EXPORT_FAILED",

  DOWNLOAD_TABLE_FETCHING: "FINAL_SUBMISSION_TYPES.DOWNLOAD_TABLE_FETCHING",
  DOWNLOAD_TABLE_FETCHED: "FINAL_SUBMISSION_TYPES.DOWNLOAD_TABLE_FETCHED",
  DOWNLOAD_TABLE_FAILED: "FINAL_SUBMISSION_TYPES.DOWNLOAD_TABLE_FAILED",
};
