export const LOGIN_DATA_TYPES={
    LOGIN_DATA_FETCHING:"LOGIN_DATA_FETCHING.LOGIN_DATA_FETCHING",
    LOGIN_DATA_FETCHED:"LOGIN_DATA_FETCHED.LOGIN_DATA_FETCHED",
    LOGIN_DATA_FAILED:"LOGIN_DATA_FAILED.LOGIN_DATA_FAILED",
    LOGIN_CHANGE_DATA_FETCHING:" LOGIN_CHANGE_DATA_FETCHING. LOGIN_CHANGE_DATA_FETCHING",
    LOGIN_CHANGE_DATA_FETCHED:"LOGIN_CHANGE_DATA_FETCHED.LOGIN_CHANGE_DATA_FETCHED",
    LOGIN_CHANGE_DATA_FAILED:"LOGIN_CHANGE_DATA_FAILED. LOGIN_CHANGE_DATA_FAILED",
    // LANGUAGE_CHANGE_DATA:" LANGUAGE_CHANGE_DATA. LANGUAGE_CHANGE_DATA",
}